apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deploy
spec:
  selector:
    matchLabels:
      app: app
  revisionHistoryLimit: 3
  strategy:
    type: RollingUpdate
  replicas: 1
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
        - name: nodejs
          image: '{{ .Values.werf.image.app }}'
          workingDir: /app
          resources:
            limits:
              cpu: "0.25"
          env:
            - name: MONGO_URI
              value: '{{ .Values.mongodb.uri }}'
            - name: EKP_PLUGIN_ID
              value: {{ .Chart.Name }}
            - name: EKP_PLUGIN_NAME
              value: '.'
            - name: REDIS_HOST
              value: '{{ .Release.Name }}-redis-master'
            - name: BSC_JSON_RPC_PROVIDER
              value: '{{ .Values.bsc.rpc }}'
            - name: NODE_ENV
              value: '{{ .Values.werf.env | default "production" }}'
            - name: PROXY_HOST
              value: '{{ .Values.proxy.host }}'
            - name: PROXY_PORT
              value: '{{ .Values.proxy.port }}'
            - name: PUBLIC_URL
              value: 'https://{{ .Release.Name }}.{{ .Values.ingress.hostname }}'
          ports:
            - containerPort: 3001
              protocol: TCP
